#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I../Boost/Boost-Source -ISource/Simulation/Agents
CFLAGS = -std=c++11 -Wall -fPIC
RESINC = 
LIBDIR = -L../Boost/Boost-Source/stage/lib
LIB = ../Boost/Boost-Source/stage/lib/libboost_chrono.a ../Boost/Boost-Source/stage/lib/libboost_date_time.a ../Boost/Boost-Source/stage/lib/libboost_filesystem.a ../Boost/Boost-Source/stage/lib/libboost_regex.a ../Boost/Boost-Source/stage/lib/libboost_serialization.a ../Boost/Boost-Source/stage/lib/libboost_system.a ../Boost/Boost-Source/stage/lib/libboost_thread.a ../Boost/Boost-Source/stage/lib/libboost_wserialization.a
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/FMI.so

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/FMI.so

OBJ_DEBUG = $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_HeatGains.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_WindowsOpening.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_RandomWeibull.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Presence.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Lights.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_EnergyPlus.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_BlindUsage.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Agents.o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Activity.o $(OBJDIR_DEBUG)/Source/Store/VariableStore.o $(OBJDIR_DEBUG)/fmuTemplate.o $(OBJDIR_DEBUG)/Source/Utility.o $(OBJDIR_DEBUG)/Source/Simulation/Zone/Zone_Manager.o $(OBJDIR_DEBUG)/Source/Simulation/Zone/Zone.o $(OBJDIR_DEBUG)/Source/Simulation/SimulationConfig.o $(OBJDIR_DEBUG)/Source/Simulation/Simulation.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Out.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Metabolic.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_IT.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Cooking.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Passive.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Cleaning.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Audio_Visual.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/StateMachine.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Washing_Appliance.o $(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus/EP_ReadIDF.o $(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus/EP_IDFObject.o $(OBJDIR_DEBUG)/Source/Simulation/Componants/Componant.o $(OBJDIR_DEBUG)/Source/Simulation/Componants/Comp_BuildingSim.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/Agent.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Washing.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Sleep.o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Present.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_HeatGains.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_WindowsOpening.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_RandomWeibull.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Presence.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Lights.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_EnergyPlus.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_BlindUsage.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Agents.o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Activity.o $(OBJDIR_RELEASE)/Source/Store/VariableStore.o $(OBJDIR_RELEASE)/fmuTemplate.o $(OBJDIR_RELEASE)/Source/Utility.o $(OBJDIR_RELEASE)/Source/Simulation/Zone/Zone_Manager.o $(OBJDIR_RELEASE)/Source/Simulation/Zone/Zone.o $(OBJDIR_RELEASE)/Source/Simulation/SimulationConfig.o $(OBJDIR_RELEASE)/Source/Simulation/Simulation.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Out.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Metabolic.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_IT.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Cooking.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Passive.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Cleaning.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Audio_Visual.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/StateMachine.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Washing_Appliance.o $(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus/EP_ReadIDF.o $(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus/EP_IDFObject.o $(OBJDIR_RELEASE)/Source/Simulation/Componants/Componant.o $(OBJDIR_RELEASE)/Source/Simulation/Componants/Comp_BuildingSim.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/Agent.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Washing.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Sleep.o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Present.o

all: before_build build_debug build_release after_build

clean: clean_debug clean_release

before_build: 

after_build: 
	cp ./bin/Debug/libFMI.so ./FMI.so
	cp ./bin/Debug/libFMI.so ../../../EnergyPlus/tmp-fmus/agentFMU.fmu_FMI/binaries/linux64/FMI.so

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/Source/Simulation/Models || mkdir -p $(OBJDIR_DEBUG)/Source/Simulation/Models
	test -d $(OBJDIR_DEBUG)/Source/Store || mkdir -p $(OBJDIR_DEBUG)/Source/Store
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/Source || mkdir -p $(OBJDIR_DEBUG)/Source
	test -d $(OBJDIR_DEBUG)/Source/Simulation/Zone || mkdir -p $(OBJDIR_DEBUG)/Source/Simulation/Zone
	test -d $(OBJDIR_DEBUG)/Source/Simulation || mkdir -p $(OBJDIR_DEBUG)/Source/Simulation
	test -d $(OBJDIR_DEBUG)/Source/Simulation/Agents || mkdir -p $(OBJDIR_DEBUG)/Source/Simulation/Agents
	test -d $(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus || mkdir -p $(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus
	test -d $(OBJDIR_DEBUG)/Source/Simulation/Componants || mkdir -p $(OBJDIR_DEBUG)/Source/Simulation/Componants

after_debug: 

build_debug: before_debug out_debug after_debug

debug: before_build build_debug after_build

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) -shared $(LIBDIR_DEBUG) $(OBJ_DEBUG)  -o $(OUT_DEBUG) $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_HeatGains.o: Source/Simulation/Models/Model_HeatGains.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_HeatGains.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_HeatGains.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_WindowsOpening.o: Source/Simulation/Models/Model_WindowsOpening.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_WindowsOpening.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_WindowsOpening.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_RandomWeibull.o: Source/Simulation/Models/Model_RandomWeibull.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_RandomWeibull.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_RandomWeibull.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Presence.o: Source/Simulation/Models/Model_Presence.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_Presence.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Presence.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Lights.o: Source/Simulation/Models/Model_Lights.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_Lights.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Lights.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_EnergyPlus.o: Source/Simulation/Models/Model_EnergyPlus.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_EnergyPlus.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_EnergyPlus.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_BlindUsage.o: Source/Simulation/Models/Model_BlindUsage.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_BlindUsage.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_BlindUsage.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Agents.o: Source/Simulation/Models/Model_Agents.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_Agents.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Agents.o

$(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Activity.o: Source/Simulation/Models/Model_Activity.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Models/Model_Activity.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Models/Model_Activity.o

$(OBJDIR_DEBUG)/Source/Store/VariableStore.o: Source/Store/VariableStore.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Store/VariableStore.cpp -o $(OBJDIR_DEBUG)/Source/Store/VariableStore.o

$(OBJDIR_DEBUG)/fmuTemplate.o: fmuTemplate.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c fmuTemplate.cpp -o $(OBJDIR_DEBUG)/fmuTemplate.o

$(OBJDIR_DEBUG)/Source/Utility.o: Source/Utility.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Utility.cpp -o $(OBJDIR_DEBUG)/Source/Utility.o

$(OBJDIR_DEBUG)/Source/Simulation/Zone/Zone_Manager.o: Source/Simulation/Zone/Zone_Manager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Zone/Zone_Manager.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Zone/Zone_Manager.o

$(OBJDIR_DEBUG)/Source/Simulation/Zone/Zone.o: Source/Simulation/Zone/Zone.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Zone/Zone.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Zone/Zone.o

$(OBJDIR_DEBUG)/Source/Simulation/SimulationConfig.o: Source/Simulation/SimulationConfig.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/SimulationConfig.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/SimulationConfig.o

$(OBJDIR_DEBUG)/Source/Simulation/Simulation.o: Source/Simulation/Simulation.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Simulation.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Simulation.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Out.o: Source/Simulation/Agents/State_Out.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Out.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Out.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Metabolic.o: Source/Simulation/Agents/State_Metabolic.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Metabolic.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Metabolic.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_IT.o: Source/Simulation/Agents/State_IT.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_IT.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_IT.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Cooking.o: Source/Simulation/Agents/State_Cooking.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Cooking.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Cooking.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Passive.o: Source/Simulation/Agents/State_Passive.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Passive.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Passive.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Cleaning.o: Source/Simulation/Agents/State_Cleaning.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Cleaning.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Cleaning.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Audio_Visual.o: Source/Simulation/Agents/State_Audio_Visual.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Audio_Visual.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Audio_Visual.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/StateMachine.o: Source/Simulation/Agents/StateMachine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/StateMachine.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/StateMachine.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State.o: Source/Simulation/Agents/State.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Washing_Appliance.o: Source/Simulation/Agents/State_Washing_Appliance.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Washing_Appliance.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Washing_Appliance.o

$(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus/EP_ReadIDF.o: Source/Simulation/EnergyPlus/EP_ReadIDF.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/EnergyPlus/EP_ReadIDF.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus/EP_ReadIDF.o

$(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus/EP_IDFObject.o: Source/Simulation/EnergyPlus/EP_IDFObject.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/EnergyPlus/EP_IDFObject.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus/EP_IDFObject.o

$(OBJDIR_DEBUG)/Source/Simulation/Componants/Componant.o: Source/Simulation/Componants/Componant.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Componants/Componant.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Componants/Componant.o

$(OBJDIR_DEBUG)/Source/Simulation/Componants/Comp_BuildingSim.o: Source/Simulation/Componants/Comp_BuildingSim.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Componants/Comp_BuildingSim.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Componants/Comp_BuildingSim.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/Agent.o: Source/Simulation/Agents/Agent.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/Agent.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/Agent.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Washing.o: Source/Simulation/Agents/State_Washing.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Washing.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Washing.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Sleep.o: Source/Simulation/Agents/State_Sleep.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Sleep.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Sleep.o

$(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Present.o: Source/Simulation/Agents/State_Present.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Source/Simulation/Agents/State_Present.cpp -o $(OBJDIR_DEBUG)/Source/Simulation/Agents/State_Present.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/Source/Simulation/Models
	rm -rf $(OBJDIR_DEBUG)/Source/Store
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/Source
	rm -rf $(OBJDIR_DEBUG)/Source/Simulation/Zone
	rm -rf $(OBJDIR_DEBUG)/Source/Simulation
	rm -rf $(OBJDIR_DEBUG)/Source/Simulation/Agents
	rm -rf $(OBJDIR_DEBUG)/Source/Simulation/EnergyPlus
	rm -rf $(OBJDIR_DEBUG)/Source/Simulation/Componants

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/Source/Simulation/Models || mkdir -p $(OBJDIR_RELEASE)/Source/Simulation/Models
	test -d $(OBJDIR_RELEASE)/Source/Store || mkdir -p $(OBJDIR_RELEASE)/Source/Store
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/Source || mkdir -p $(OBJDIR_RELEASE)/Source
	test -d $(OBJDIR_RELEASE)/Source/Simulation/Zone || mkdir -p $(OBJDIR_RELEASE)/Source/Simulation/Zone
	test -d $(OBJDIR_RELEASE)/Source/Simulation || mkdir -p $(OBJDIR_RELEASE)/Source/Simulation
	test -d $(OBJDIR_RELEASE)/Source/Simulation/Agents || mkdir -p $(OBJDIR_RELEASE)/Source/Simulation/Agents
	test -d $(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus || mkdir -p $(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus
	test -d $(OBJDIR_RELEASE)/Source/Simulation/Componants || mkdir -p $(OBJDIR_RELEASE)/Source/Simulation/Componants

after_release: 

build_release: before_release out_release after_release

release: before_build build_release after_build

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) -shared $(LIBDIR_RELEASE) $(OBJ_RELEASE)  -o $(OUT_RELEASE) $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_HeatGains.o: Source/Simulation/Models/Model_HeatGains.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_HeatGains.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_HeatGains.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_WindowsOpening.o: Source/Simulation/Models/Model_WindowsOpening.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_WindowsOpening.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_WindowsOpening.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_RandomWeibull.o: Source/Simulation/Models/Model_RandomWeibull.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_RandomWeibull.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_RandomWeibull.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Presence.o: Source/Simulation/Models/Model_Presence.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_Presence.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Presence.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Lights.o: Source/Simulation/Models/Model_Lights.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_Lights.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Lights.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_EnergyPlus.o: Source/Simulation/Models/Model_EnergyPlus.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_EnergyPlus.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_EnergyPlus.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_BlindUsage.o: Source/Simulation/Models/Model_BlindUsage.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_BlindUsage.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_BlindUsage.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Agents.o: Source/Simulation/Models/Model_Agents.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_Agents.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Agents.o

$(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Activity.o: Source/Simulation/Models/Model_Activity.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Models/Model_Activity.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Models/Model_Activity.o

$(OBJDIR_RELEASE)/Source/Store/VariableStore.o: Source/Store/VariableStore.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Store/VariableStore.cpp -o $(OBJDIR_RELEASE)/Source/Store/VariableStore.o

$(OBJDIR_RELEASE)/fmuTemplate.o: fmuTemplate.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c fmuTemplate.cpp -o $(OBJDIR_RELEASE)/fmuTemplate.o

$(OBJDIR_RELEASE)/Source/Utility.o: Source/Utility.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Utility.cpp -o $(OBJDIR_RELEASE)/Source/Utility.o

$(OBJDIR_RELEASE)/Source/Simulation/Zone/Zone_Manager.o: Source/Simulation/Zone/Zone_Manager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Zone/Zone_Manager.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Zone/Zone_Manager.o

$(OBJDIR_RELEASE)/Source/Simulation/Zone/Zone.o: Source/Simulation/Zone/Zone.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Zone/Zone.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Zone/Zone.o

$(OBJDIR_RELEASE)/Source/Simulation/SimulationConfig.o: Source/Simulation/SimulationConfig.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/SimulationConfig.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/SimulationConfig.o

$(OBJDIR_RELEASE)/Source/Simulation/Simulation.o: Source/Simulation/Simulation.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Simulation.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Simulation.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Out.o: Source/Simulation/Agents/State_Out.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Out.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Out.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Metabolic.o: Source/Simulation/Agents/State_Metabolic.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Metabolic.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Metabolic.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_IT.o: Source/Simulation/Agents/State_IT.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_IT.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_IT.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Cooking.o: Source/Simulation/Agents/State_Cooking.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Cooking.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Cooking.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Passive.o: Source/Simulation/Agents/State_Passive.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Passive.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Passive.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Cleaning.o: Source/Simulation/Agents/State_Cleaning.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Cleaning.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Cleaning.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Audio_Visual.o: Source/Simulation/Agents/State_Audio_Visual.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Audio_Visual.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Audio_Visual.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/StateMachine.o: Source/Simulation/Agents/StateMachine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/StateMachine.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/StateMachine.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State.o: Source/Simulation/Agents/State.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Washing_Appliance.o: Source/Simulation/Agents/State_Washing_Appliance.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Washing_Appliance.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Washing_Appliance.o

$(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus/EP_ReadIDF.o: Source/Simulation/EnergyPlus/EP_ReadIDF.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/EnergyPlus/EP_ReadIDF.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus/EP_ReadIDF.o

$(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus/EP_IDFObject.o: Source/Simulation/EnergyPlus/EP_IDFObject.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/EnergyPlus/EP_IDFObject.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus/EP_IDFObject.o

$(OBJDIR_RELEASE)/Source/Simulation/Componants/Componant.o: Source/Simulation/Componants/Componant.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Componants/Componant.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Componants/Componant.o

$(OBJDIR_RELEASE)/Source/Simulation/Componants/Comp_BuildingSim.o: Source/Simulation/Componants/Comp_BuildingSim.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Componants/Comp_BuildingSim.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Componants/Comp_BuildingSim.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/Agent.o: Source/Simulation/Agents/Agent.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/Agent.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/Agent.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Washing.o: Source/Simulation/Agents/State_Washing.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Washing.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Washing.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Sleep.o: Source/Simulation/Agents/State_Sleep.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Sleep.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Sleep.o

$(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Present.o: Source/Simulation/Agents/State_Present.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Source/Simulation/Agents/State_Present.cpp -o $(OBJDIR_RELEASE)/Source/Simulation/Agents/State_Present.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/Source/Simulation/Models
	rm -rf $(OBJDIR_RELEASE)/Source/Store
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/Source
	rm -rf $(OBJDIR_RELEASE)/Source/Simulation/Zone
	rm -rf $(OBJDIR_RELEASE)/Source/Simulation
	rm -rf $(OBJDIR_RELEASE)/Source/Simulation/Agents
	rm -rf $(OBJDIR_RELEASE)/Source/Simulation/EnergyPlus
	rm -rf $(OBJDIR_RELEASE)/Source/Simulation/Componants

.PHONY: before_build after_build before_debug after_debug clean_debug before_release after_release clean_release

